---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-graphql
  namespace: iot
  labels:
    app: api-graphql
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.api-graphql: glob:prod-*
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-graphql
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: api-graphql
    spec:
      containers:
      - name: api-graphql
        image: docker.pkg.github.com/iot-for-tillgenglighet/api-graphql/api-graphql:prod-0a98ab6bb5daea8ed01ab37d6a314a27cc52a7e1
        imagePullPolicy: IfNotPresent
        env:
        - name: API_GQL_FEDERATION_PORT
          value: '8989'
        - name: API_GQL_FEDERATION_SVCS
          value: 'api-problemreport-service.iot.svc.cluster.local:80,api-snowdepth-service.iot.svc.cluster.local:80,api-temperature-service.iot.svc.cluster.local:80,iot-device-registry-service.iot.svc.cluster.local:80'
        ports:
        - containerPort: 8989
          name: http
          protocol: TCP
      imagePullSecrets:
      - name: regcred
