---
apiVersion: v1
kind: Service
metadata:
  name: api-temperature-service
  namespace: iot
  labels:
    app: iot
spec:
  type: NodePort
  selector:
    app: iot
  ports:
    - name: http
      port: 8282
      targetPort: 8282
      protocol: TCP