---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-temperature
  namespace: iot
  labels:
    app: api-temperature
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.api-temperature: glob:prod-*
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-temperature
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: api-temperature
    spec:
      containers:
      - name: api-temperature
        image: docker.pkg.github.com/iot-for-tillgenglighet/api-temperature/api-temperature:prod-267d710ed294ae6eef9e09405e1b9438b7a2f195
        imagePullPolicy: IfNotPresent
        env:
        - name: TEMPERATURE_DB_HOST
          valueFrom:
            secretKeyRef:
              name: api-temperature-envvar
              key: db-host
        - name: TEMPERATURE_DB_NAME
          valueFrom:
            secretKeyRef:
              name: api-temperature-envvar
              key: db-name
        - name: TEMPERATURE_DB_USER
          valueFrom:
            secretKeyRef:
              name: api-temperature-envvar
              key: db-user
        - name: TEMPERATURE_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: api-temperature-envvar
              key: db-password
        - name: TEMPERATURE_API_PORT
          value: '8181'
        - name: RABBITMQ_HOST
          value: rabbitmq.iot.svc.cluster.local
        ports:
        - containerPort: 8181
          name: http
          protocol: TCP
      imagePullSecrets:
      - name: regcred
