---
apiVersion: v1
kind: Service
metadata: 
  name: api-snowdepth-service
  namespace: iot
  labels:
    app: api-snowdepth
spec:
  type: NodePort
  selector:
    app: api-snowdepth
  ports:
    - name: http
      port: 80
      targetPort: 8282
      protocol: TCP
