---
apiVersion: v1
kind: Service
metadata:
  name: api-temperature-service
  namespace: iot
  labels:
    app: api-temperature
spec:
  type: NodePort
  selector:
    app: api-temperature
  ports:
    - name: http
      port: 80
      targetPort: 8282
      protocol: TCP