---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-temperature
  namespace: iot
  labels:
    app: api-temperature
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-temperature
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: api-temperature
    spec:
      containers:
      - name: api-temperature
        image: docker.pkg.github.com/iot-for-tillgenglighet/api-temperature/api-temperature:e3744f3c39f6da6b2c328cbfab6b808290c1d77e
        imagePullPolicy: IfNotPresent
        env:
        - name: TEMPERATURE_DB_HOST
          valueFrom:
            secretKeyRef:
              name: api-temperature-envvar
              key: db-host
        - name: TEMPERATURE_DB_NAME
          valueFrom:
            secretKeyRef:
              name: api-temperature-envvar
              key: db-name
        - name: TEMPERATURE_DB_USER
          valueFrom:
            secretKeyRef:
              name: api-temperature-envvar
              key: db-user
        - name: TEMPERATURE_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: api-temperature-envvar
              key: db-password
        - name: TEMPERATURE_API_PORT
          value: '8282'
        ports:
        - containerPort: 8282
          name: http
          protocol: TCP
      imagePullSecrets:
      - name: regcred