---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-problemreport
  namespace: iot
  labels:
    app: api-problemreport
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.api-problemreport: glob:prod-*
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-problemreport
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: api-problemreport
    spec:
      containers:
      - name: api-problemreport
        image: docker.pkg.github.com/iot-for-tillgenglighet/api-problemreport/api-problemreport:prod-73cb6e81930c30cdd5819590690feb4c9ad1eb9d
        imagePullPolicy: IfNotPresent
        env:
        - name: PROBLEMREPORT_DB_HOST
          valueFrom:
            secretKeyRef:
              name: api-problemreport-envvar
              key: db-host
        - name: PROBLEMREPORT_DB_USER
          valueFrom:
            secretKeyRef:
              name: api-problemreport-envvar
              key: db-user
        - name: PROBLEMREPORT_DB_NAME
          valueFrom:
            secretKeyRef:
              name: api-problemreport-envvar
              key: db-name
        - name: PROBLEMREPORT_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: api-problemreport-envvar
              key: db-password
        - name: PROBLEMREPORT_DB_SSLMODE
          value: 'require'
        - name: PROBLEMREPORT_API_PORT
          value: '8383'
        - name: RABBITMQ_HOST
          value: 'rabbitmq.iot.svc.cluster.local'
        ports:
        - containerPort: 8383
          name: http
          protocol: TCP
      imagePullSecrets:
      - name: regcred



