---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-mqtt-miun
  namespace: iot
  labels:
    app: ingress-mqtt-miun
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.ingress-mqtt: glob:prod-*
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-mqtt-miun
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: ingress-mqtt-miun
    spec:
      containers:
      - name: ingress-mqtt-miun
        image: docker.pkg.github.com/iot-for-tillgenglighet/ingress-mqtt/ingress-mqtt:prod-0f5178e0e05e22aac889c7d5ff237b3ae9a20304
        imagePullPolicy: IfNotPresent
        env:
          - name: MQTT_HOST
            valueFrom:
              secretKeyRef:
                name: ingress-mqtt-miun-envvar
                key: mqtt-host
          - name: MQTT_PORT
            valueFrom:
              secretKeyRef:
                name: ingress-mqtt-miun-envvar
                key: mqtt-port
          - name: MQTT_TOPIC
            valueFrom:
              secretKeyRef:
                name: ingress-mqtt-miun-envvar
                key: mqtt-topic
          - name: MQTT_USER
            valueFrom:
              secretKeyRef:
                name: ingress-mqtt-miun-envvar
                key: mqtt-user
          - name: MQTT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ingress-mqtt-miun-envvar
                key: mqtt-password
          - name: MQTT_TLS_DISABLED
            valueFrom:
              secretKeyRef:
                name: ingress-mqtt-miun-envvar
                key: mqtt-tls-disabled
          - name: RABBITMQ_USER
            valueFrom:
              secretKeyRef:
                name: ingress-mqtt-envvar
                key: rabbitmq-user
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ingress-mqtt-envvar
                key: rabbitmq-password
          - name: RABBITMQ_HOST
            value: "rabbitmq.iot.svc.cluster.local"
      imagePullSecrets:
        - name: regcred
