---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-device-registry
  namespace: iot
  labels:
    app: iot-device-registry
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.iot-device-registry: glob:prod-*
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-device-registry
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: iot-device-registry
    spec:
      containers:
      - name: iot-device-registry
        image: docker.pkg.github.com/iot-for-tillgenglighet/iot-device-registry/iot-device-registry:prod-14cb5f4b9b29d1d150553e12d0506625d53f7a87
        imagePullPolicy: IfNotPresent
        env:
        - name: SERVICE_PORT
          value: '8080'
        - name: RABBITMQ_HOST
          value: rabbitmq.iot.svc.cluster.local
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      imagePullSecrets:
      - name: regcred
