apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: iot-hub-gateway
  namespace: iot
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: "iotsundsvall-credential"
    hosts:
    - "*"
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"